# 網站設置
title: 殷慈遠的設計工作室 # 預設網站標題
header_title: "殷慈遠"  # 預設頁首標題
description: 創意字型設計與作品展示
url: "https://erikyin.net"
baseurl: ""

# 添加其他配置...

sass:
  sass_dir: _sass
  style: compressed

verbose: true

# 部落格設置
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "/blog/page:num/"

# 添加部落格相關的集合
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/