# 網站設置
title: 殷慈遠的設計工作室 # 預設網站標題
header_title: "殷慈遠"  # 預設頁首標題
description: 創意字型設計與作品展示
url: "https://erikyin.net"
baseurl: ""
encoding: utf-8

sass:
  sass_dir: _sass
  style: compressed

verbose: true


# 部落格文章的永久連結格式
permalink: /blog/:title/

# 分類和標籤設置
collections:
  categories:
    output: true
    permalink: /blog/category/:name/
  tags:
    output: true
    permalink: /blog/tag/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "殷慈遠"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"

# 部落格相關設置
plugins:
  - jekyll-archives # 分類和標籤設置
  - jekyll-paginate # 分頁設置
  - jekyll-target-blank # 自動轉換連結

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /blog/category/:name/
    tag: /blog/tag/:name/  

paginate: 10
paginate_path: "/blog/page:num/"

markdown: kramdown
kramdown:
  toc_levels: 2..3
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# 閱讀時間設置
words_per_minute: 250

# RSS Feed 設置
feed:
  path: feed.xml
  posts_limit: 20